title: muOS
description: Custom Firmware (CFW) primarily for handheld devices. Configurable, themeable, friendly, easy-to-use.
theme: just-the-docs

url: https://muos.dev

color_scheme: muos

aux_links:
  Download: https://dl.muos.dev/
  Discord: https://discord.gg/USS5ybVtDz
  Support: https://ko-fi.com/xonglebongle
